name: Sync Fork

on:
  schedule:
  # Runs every day at 00:00 UTC
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: quarto-dev
          base: main
